version: '3.1'

services:

  ghost:
    image: ghost:3-alpine
    restart: always
    ports:
      - 7676:2368
    volumes:  
      - /data:/var/lib/ghost/content
    environment:
      database__client: mysql
      database__connection__host: ${DB_CONNECTION_HOST}
      database__connection__port: 3306
      database__connection__user: ${DB_USER}
      database__connection__password: ${DB_PASSWORD}
      database__connection__database: ghost
      database__connection__ssl: "Amazon RDS"
      url: http://${INSTANCE_IP}:7676

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
        - 3333:80
    environment:
        PMA_HOST: ${DB_CONNECTION_HOST}:3306
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
