version: '3.1'

services:

  ghost:
    image: ghost:3-alpine
    restart: always
    ports:
      - 7676:2368
    volumes:  
      - ./blog:/var/lib/ghost/content
    environment:
      database__client: mysql
      database__connection__host: terraform-20210507074810311700000001.cb3e9cb9eatj.eu-west-1.rds.amazonaws.com
      database__connection__port: 3306
      database__connection__user: root
      database__connection__password: helloworld
      database__connection__database: ghost
      database__connection__ssl: "Amazon RDS"
      url: http://localhost:7676

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
        - 3333:80
    environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: password